Home page redesign
ACMGitHub/WSCACM pull request #33
Opened 2024-12-15 06:24 UTC by Typher7

Carousel added to landing page.

2024-12-17 23:04 UTC, Brogoming requested changes
Delete duplicate photos, make these changes then we will go from there, I'm not 100% sure about our initial idea but do these changes and we can go from there

2024-12-17 23:04 UTC, Brogoming commented on src/routes/+page.svelte
> +				let:Controls
Remove the indicators and controls, when scrolling the lay over the nav bar

2024-12-17 23:04 UTC, Brogoming commented on src/routes/+page.svelte
> +	<div class="md:col-span-2 justify-between px-4 pb-10">
I would like there to be no padding on the x-axis and shorten the gap between the carousel and the words

2024-12-17 23:04 UTC, Brogoming commented on src/routes/+page.svelte
> +<div class="grid md:grid-cols-3 gap-8 px-4">
I would like there to be no padding on the x-axis, I would like the components to be flush with the sides

2024-12-17 23:04 UTC, Brogoming commented on src/routes/+page.svelte
> +		<p class="text-center text-xl py-20">
py-20 seems a bit much

2024-12-27 10:23 UTC, Typher7 commented on src/routes/+page.svelte
> +				let:Controls
Do you mean hiding them on hover?

2024-12-27 10:27 UTC, Typher7 commented on src/routes/+page.svelte
> +		<p class="text-center text-xl py-20">
halved it to 10

2024-12-27 10:28 UTC, Typher7 commented on src/routes/+page.svelte
> +<div class="grid md:grid-cols-3 gap-8 px-4">
removed it, but the 'y-axis' padding comes from the layout

2024-12-29 19:44 UTC, Brogoming commented on src/routes/+page.svelte
> +				let:Controls
no full removal because scrolling they layover the nav bar

2024-12-29 19:46 UTC, Brogoming commented on src/routes/+page.svelte
> +<div class="grid md:grid-cols-3 gap-8 px-4">
We can work on that

2024-12-29 21:43 UTC, Typher7 commented on src/routes/+page.svelte
> +				let:Controls
I've fixed the layover problem, let me know if you still want the ctrls and ind removed

2024-12-29 23:50 UTC, ACMGitHub approved these changes

2024-12-29 23:51 UTC, merged